name: Build VB.NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2
    - uses: NuGet/setup-nuget@v1.0.2
    - run: nuget restore SimpleFrameworkApp.sln
    - run: msbuild 'Source/SteamCMD GUI.sln'
